entry.id,jurisdiction,date.announced,date.implemented,category,type,primary.source.(news.release.or.specific.resource),secondary.source,action,level,indigenous.population.group,who,what,effective.until,colour,alpha
AB033,Alberta,18336,18336,closures/openings,education,https://www.alberta.ca/release.cfm?xID=69818C355F188-C2A3-F5C6-875A2A33929D5C05,Not applicable,Tightening,Provincial/territorial,FALSE,"government of alberta, chief medical officer of health, premier",closure of elementar,18988,red,AB
AB035,Alberta,18336,18336,closures/openings,education,https://www.alberta.ca/release.cfm?xID=69818C355F188-C2A3-F5C6-875A2A33929D5C05#toc-1,Not applicable,Tightening,Provincial/territorial,FALSE,"government of alberta, chief medical officer of health, premier",in-person classes ar,18988,red,AB
AB216,Alberta,18590,18596,closures/openings,education,https://web.archive.org/web/20201125051018/https://www.alberta.ca/enhanced-public-health-measures.aspx,Not applicable,Tightening,Provincial/territorial,FALSE,government of alberta,mandated home learni,18638,red,AB
AB337,Alberta,18751,18754,closures/openings,education,https://www.alberta.ca/release.cfm?xID=780944289E67F-AB21-1393-1723D64CDEC6F61D,Not applicable,Tightening,Provincial/territorial,FALSE,government of alberta,shifted all k–12 l,18772,red,AB
BC008,British Columbia,18337,18337,closures/openings,education,https://www2.gov.bc.ca/assets/gov/health/about-bc-s-health-care-system/office-of-the-provincial-health-officer/reports-publications/covid-19-pho-class-order-mass-gatherings.pdf,https://www.ubc.ca/campus-notifications/,Tightening,Provincial/territorial,FALSE,"government of british columbia, provincial health officer",closure of post-seco,18412,red,BC
BC018,British Columbia,,18338,closures/openings,education,http://www.bccdc.ca/health-info/diseases-conditions/covid-19/childcare-schools,https://www2.gov.bc.ca/assets/gov/health/about-bc-s-health-care-system/office-of-the-provincial-health-officer/reports-publications/covid-19-pho-class-order-mass-gatherings.pdf,Tightening,Provincial/territorial,FALSE,"government of british columbia, provincial health officer",closures of public e,18412,red,BC
BC028,British Columbia,18351,18350,closures/openings,education,https://news.gov.bc.ca/releases/2020HLTH0115-000594,https://www.openschool.bc.ca/keeplearning/,Tightening,Provincial/territorial,FALSE,"minister of health, provincial health officer, government of british columbia",made online resource,18988,red,BC
MB025,Manitoba,18336,18344,closures/openings,education,https://news.gov.mb.ca/news/index.html?item=46957,Not applicable,Tightening,Provincial/territorial,FALSE,public health officials,closure of elementar,18364,red,MB
MB036,Manitoba,18352,18352,closures/openings,education,https://news.gov.mb.ca/news/index.html?item=47341&posted=2020-03-31,Not applicable,Tightening,Provincial/territorial,FALSE,government of manitoba,closure of elementar,18988,red,MB
NB017,New Brunswick,18340,18340,closures/openings,education,https://www2.gnb.ca/content/gnb/en/news/news_release.2020.03.0139.html,Not applicable,Tightening,Provincial/territorial,FALSE,"office of the premier, government of new brunswick",closure of post-seco,18988,red,NB
NB033,New Brunswick,18354,18354,closures/openings,education,https://www2.gnb.ca/content/gnb/en/news/news_release.2020.04.0176.html,Not applicable,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,announced that k–1,18988,red,NB
NB348,New Brunswick,18740,18740,closures/openings,education,https://www2.gnb.ca/content/gnb/en/corporate/promo/covid-19/news/news_release.2021.04.0315.html,https://www.cbc.ca/news/canada/new-brunswick/new-brunswick-covid-19-update-april-22-1.5999702,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,high school students,18988,red,NB
NL009,Newfoundland and Labrador,18337,18338,closures/openings,education,https://www.nlesd.ca/families/doc/c19-sci-03162020.pdf,Not applicable,Tightening,Provincial/territorial,FALSE,newfoundland and labrador english school district,closure of elementar,18988,red,NL
NL027,Newfoundland and Labrador,18354,18354,closures/openings,education,https://www.gov.nl.ca/releases/2020/exec/0402n02/,Not applicable,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,cancelled elementary,18988,red,NL
NL066,Newfoundland and Labrador,18397,18397,closures/openings,education,https://www.gov.nl.ca/releases/2020/eecd/0515n01/,Not applicable,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,announced that schoo,18988,red,NL
NS027,Nova Scotia,18351,18351,closures/openings,education,https://novascotia.ca/news/release/?id=20200330004,Not applicable,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,closure of elementar,18383,red,NS
NS054,Nova Scotia,18380,18380,closures/openings,education,https://novascotia.ca/news/release/?id=20200428005,Not applicable,Tightening,Provincial/territorial,FALSE,department of education and early childhood development,extended closure of ,18401,red,NS
NS250,Nova Scotia,18743,18743,closures/openings,education,https://novascotia.ca/news/release/?id=20210426006,Not applicable,Tightening,Provincial/territorial,FALSE,department of health and wellness,"for all of n.s., sto",18988,red,NS
NS257,Nova Scotia,18744,18745,closures/openings,education,https://novascotia.ca/news/release/?id=20210427003,Not applicable,Tightening,Provincial/territorial,FALSE,"premier, department of health and wellness","for all of n.s., clo",18988,red,NS
NT008,Northwest Territories,18337,18337,closures/openings,education,https://www.ece.gov.nt.ca/en/services/education-culture-and-employment-covid-19-updates/information-jk-12-schools,Not applicable,Tightening,Provincial/territorial,FALSE,government of the northwest territories,closure of public el,18366,red,NT
NT026,Northwest Territories,18338,18344,closures/openings,education,https://www.gov.nt.ca/en/program-and-service-availability-during-covid-19,https://www.myyellowknifenow.com/47094/aurora-college-all-classes-suspended-starting-march-23rd/,Tightening,Provincial/territorial,FALSE,government of the northwest territories,closure of post-seco,18988,red,NT
NT027,Northwest Territories,18346,18346,closures/openings,education,https://www.ece.gov.nt.ca/en/services/education-culture-and-employment-covid-19-updates/information-jk-12-schools,Not applicable,Tightening,Provincial/territorial,FALSE,"district education authorities, minister of education, culture, and employment, northwest territories teachers’ association",closure of public el,18506,red,NT
NT070,Northwest Territories,18396,18396,closures/openings,education,https://www.gov.nt.ca/en/newsroom/nwt-education-leaders-agree-keep-schools-closed-remainder-2019-20-school-year-0,Not applicable,Tightening,Provincial/territorial,FALSE,"minister of education, culture and employment, the nwt teachers’ association",closed schools for t,18475,red,NT
NU007,Nunavut,18338,18338,closures/openings,education,https://www.gov.nu.ca/health/news/temporary-nunavut-wide-school-and-daycare-closures-precaution-covid-19,Not applicable,Tightening,Provincial/territorial,FALSE,minister of health,"closed elementary, m",18988,red,NU
NU011,Nunavut,18339,18339,closures/openings,education,https://gov.nu.ca/executive-and-intergovernmental-affairs/news/covid-19-daily-update-march-18-2020,Not applicable,Tightening,Provincial/territorial,FALSE,"government of nunavut, premier",closed post-secondar,18988,red,NU
NU027,Nunavut,18348,18348,closures/openings,education,https://gov.nu.ca/executive-and-intergovernmental-affairs/news/covid-19-gn-update-march-27-2020,Not applicable,Tightening,Provincial/territorial,FALSE,nunavut arctic college,extension of closure,18386,red,NU
NU028,Nunavut,18352,18352,closures/openings,education,https://gov.nu.ca/executive-and-intergovernmental-affairs/news/covid-19-gn-update-march-31-2020,Not applicable,Tightening,Provincial/territorial,FALSE,"government of nunavut, premier",extension of closure,18372,red,NU
NU037,Nunavut,18369,18369,closures/openings,education,https://www.gov.nu.ca/education/news/covid-19-department-education-services-update,Not applicable,Tightening,Provincial/territorial,FALSE,minister of education,schools closed for r,18506,red,NU
NU047,Nunavut,18376,18376,closures/openings,education,https://www.gov.nu.ca/executif-et-des-affaires-intergouvernementales/news/covid-19-gn-update-april-24-2020,Not applicable,Tightening,Provincial/territorial,FALSE,"government of nunavut, deputy premier",extended closure of ,18506,red,NU
ON009,Ontario,18333,18335,closures/openings,education,https://news.ontario.ca/opo/en/2020/03/title.html?utm_source=ondemand&utm_medium=email&utm_campaign=o,Not applicable,Tightening,Provincial/territorial,FALSE,ministry of education,closure of all publi,18358,red,ON
ON058,Ontario,18352,18352,closures/openings,education,https://news.ontario.ca/opo/en/2020/03/ontario-extends-school-and-child-care-closures-to-fight-spread-of-covid-19.html,https://news.ontario.ca/edu/en/2020/03/province-takes-steps-to-ensure-frontline-staff-can-continue-to-work.html?_ga=2.132268942.1401447723.1587393676-470745044.1584640249,Tightening,Provincial/territorial,FALSE,office of the premier,announced that publi,18513,red,ON
ON070,Ontario,18352,18358,closures/openings,education,https://news.ontario.ca/opo/en/2020/03/ontario-enacts-declaration-of-emergency-to-protect-the-public.html,https://www.ontario.ca/laws/regulation/200051?_ga=2.184837289.1860153609.1592920176-470745044.1584640249,Tightening,Provincial/territorial,FALSE,ministry of education,announced closures o,18425,red,ON
ON659,Ontario,18729,18732,closures/openings,education,https://news.ontario.ca/en/release/61106/ontario-moves-schools-to-remote-learning-following-spring-break,Not applicable,Tightening,Provincial/territorial,FALSE,"government of ontario, chief medical officer of health",private schools oper,18988,red,ON
ON660,Ontario,18729,18736,closures/openings,education,https://news.ontario.ca/en/release/61106/ontario-moves-schools-to-remote-learning-following-spring-break,Not applicable,Tightening,Provincial/territorial,FALSE,"government of ontario, chief medical officer of health",moved all publicly f,18988,red,ON
PE024,Prince Edward Island,18348,18348,closures/openings,education,https://www.princeedwardisland.ca/en/news/prince-edward-island-extends-closures-schools-daycares-non-essential-services,https://www.princeedwardisland.ca/en/news/province-announces-covid-19-related-closures,Tightening,Provincial/territorial,FALSE,chief public health officer,closure of elementar,18393,red,PE
QC066,Quebec,18343,18343,closures/openings,education,https://www.newswire.ca/fr/news-releases/pandemie-de-la-covid-19-le-premier-ministre-du-quebec-francois-legault-accentue-les-mesures-d-urgence-pour-proteger-la-population-892914211.html,Not applicable,Tightening,Provincial/territorial,FALSE,minister of education and higher education,extended closure of ,18383,red,QC
QC085,Quebec,18343,18351,closures/openings,education,https://www.newswire.ca/fr/news-releases/pandemie-de-la-covid-19-le-premier-ministre-du-quebec-francois-legault-accentue-les-mesures-d-urgence-pour-proteger-la-population-892914211.html,Not applicable,Tightening,Provincial/territorial,FALSE,office of the premier,cegep and university,18988,red,QC
QC578,Quebec,18585,18613,closures/openings,education,https://www.msss.gouv.qc.ca/ministere/salle-de-presse/communique-2454/,Not applicable,Tightening,Provincial/territorial,FALSE,ministry of health and social services,closed elementary sc,18630,red,QC
QC579,Quebec,18585,18613,closures/openings,education,https://www.msss.gouv.qc.ca/ministere/salle-de-presse/communique-2454/,Not applicable,Tightening,Provincial/territorial,FALSE,ministry of health and social services,closed secondary sch,18637,red,QC
QC626,Quebec,18611,18613,closures/openings,education,https://www.newswire.ca/fr/news-releases/pandemie-de-la-covid-19-une-pause-des-fetes-jusqu-au-10-janvier-2021-inclusivement-894009696.html,Not applicable,Tightening,Provincial/territorial,FALSE,office of the premier,for all regions of q,18637,red,QC
SK021,Saskatchewan,18337,18341,closures/openings,education,https://www.saskatchewan.ca/government/news-and-media/2020/march/16/class-suspensions,Not applicable,Tightening,Provincial/territorial,FALSE,government of saskatchewan,closure of elementar,18988,red,SK
SK085,Saskatchewan,18389,18389,closures/openings,education,https://www.saskatchewan.ca/government/news-and-media/2020/may/07/in-class-learning-suspended,Not applicable,Tightening,Provincial/territorial,FALSE,government of saskatchewan,suspended in-class l,18988,red,SK
YT010,Yukon,18339,18339,closures/openings,education,https://yukon.ca/en/news/chief-medical-officer-health-declares-public-health-emergency,Not applicable,Tightening,Provincial/territorial,FALSE,chief medical officer of health,closure of elementar,18367,red,YT
YT014,Yukon,18340,18340,closures/openings,education,https://www.yukoncollege.yk.ca/covid-19,Not applicable,Tightening,Provincial/territorial,FALSE,yukon college,closure of post-seco,18988,red,YT
YT049,Yukon,18359,18359,closures/openings,education,https://yukon.ca/en/news/face-face-classes-suspended-remainder-2019-20-school-year,Not applicable,Tightening,Provincial/territorial,FALSE,"minister of education, government of yukon",in-person classes at,18506,red,YT
